Search bar animation
uclaacm/dev-pathways pull request #56
Opened 2021-05-15 22:35 UTC by advaithg

Changes made
1. added a TypingAnimation.js in a shared folder in components
2. added label as placeholder for searchbar input, uses typing animation (queries: html/css, javascript, react)
3. added lint script (changed colors to const in stc/data/colors.js

2021-05-15 23:31 UTC, advaithg commented
Adding on - it shows the placeholder text when nothing has been typed inside and when it is not focused, i.e if you type something, backspace it and unfocus - it will show the placeholder again

2021-05-16 00:20 UTC, EinarBalan requested changes
Super psyched that you were able to figure this out @advaithg , it's looking great! And of course a big thank you to @reginawang99 for helping him out, really appreciate it :)

#### A couple notes:
- would it be possible to change the animation so that it maintains the "What do you want to learn?" and only the queries themselves are updated? This change might cause the text to overflow on smaller screens, so we would have to address that as well if it does.
-  can you add a slightly longer pause between each query cycle? Possibly 1-2 seconds? As it is right now the animation looks a bit jarring due to how quickly it cycles through.
- it's fine for now, but in the future when making changes that are mostly unrelated to the PR, we should separate these out into at least separate commits so we have a record of them in our git history. Preferably, we would even go a step further than that and make the unrelated changes on a new branch. Again, it's fine for now, but something to keep in mind for the future.

Overall though, this is looking really good so far!

2021-05-16 00:20 UTC, EinarBalan commented on package.json
> +    "lint": "eslint \"**/*.js\""
Oops, thought we already had a linter since this project was generated from Matt's template repo, but I guess not. Either way, good call adding it!

2021-05-16 00:20 UTC, EinarBalan commented on .github/workflows/build.yml
> +    - run: npm ci
Was not aware that this was a thing, but from a quick glance at the documentation, good call adding it!

2021-05-16 00:20 UTC, EinarBalan commented on src/components/SearchBar/SearchBar.css
> +:root {
Yet another good call :)

2021-05-16 00:20 UTC, EinarBalan commented on src/components/SearchBar/SearchBar.js
> +    const { value, onSubmit, onChange, onKeyDown } = props;
This isn't currently the convention for props in our project, but honestly it probably should be. Maybe we can look into refactoring other components to utilize this (outside scope of this PR though).

2021-05-16 04:25 UTC, EinarBalan approved these changes
LGTM!

2021-05-16 04:28 UTC, merged